#!/bin/bash
echo "*********************************************************"
echo "Running git pre-commit hook..."
echo "*********************************************************"

path=$(realpath "$0")

echo PATH:
echo $path

pathLength=${#path}

echo LENGTH:
echo $pathLength

let "pathLength -= 22"

echo NEW_LENGTH:
echo $pathLength

newPath=$(cut -c 1-$pathLength <<< "$path")

echo NEW_PATH:
echo $newPath

kotlinc -script $newPath/.scripts/VersionIncreaser.kts $newPath

#Adding changed version file in the commit
# shellcheck disable=SC2046
git add $newPath/.scripts/AppVersion.txt

echo "*********************************************************"
echo "Git pre-commit hook ended..."
echo "*********************************************************"

#Exit
exit 0